language: python
python:
        - "3.8"
install:
        - pip3 install -r requirements.txt
        - pip install black
        - pip install flake8
        - pip install coverage
        - pip install coveralls

before_script:
        - python manage.py migrate
        - python manage.py collectstatic --noinput

script:
        - black --check .
        - flake8 .
#         - coverage run --source=coviguard manage.py test
after_script:
        - coveralls
