# Generated by Django 4.0.3 on 2022-04-03 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Request",
            fields=[
                ("request_id", models.AutoField(primary_key=True, serialize=False)),
                ("request_display", models.CharField(max_length=100)),
                ("url", models.CharField(max_length=100)),
            ],
        ),
    ]
