# Generated by Django 4.0.3 on 2022-04-22 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scrappy", "0002_request_completed_alter_request_request_display"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="analyze_completed",
            field=models.BooleanField(default=False),
        ),
    ]
